name: Publish release
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run gradle package
        run: gradle package

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: build/compose.binaries/main/app/


